server:
  port: 8090
spring:
  application:
    name: output-demo
  cloud: 
     stream: 
        kafka: 
          binder: 
            #kafka 绑定连接的消息中间件列表。配置多个是用,号隔开，可以是单独的host,也可以是host:port
            brokers: localhost:9092
            zkNodes: localhost:2182
            auto-add-partitions: true
            auto-create-topics: true
            min-partition-count: 1
        bindings: 
          output:
            #绑定输出通道
            destination: input
            content-type: text/plain
            producer: 
              #指定消息分区的数量
              partitionCount: 1
          input: 
            destination: output