spring:
  application:
    name: 
      geteway
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://cxytiandi.com
        predicates:
        - Path=/feign
     
server: 
  port: 9002


eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:1111/eureka/